name: Frontend Deploy

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build-frontend:
    name: Building Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Establish ssh connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd /webapps/Welfare_Board_Portal/frontend
            sudo chown "$USER":"$USER" /home/"$USER"/.docker -R
            sudo chmod g+rwx "$HOME/.docker" -R
            git checkout main
            git fetch
            git pull
            docker compose -f docker-compose.yml up -d --build